nelmio_api_doc:
    documentation:
        info:
            title: Orders Management API
            description: This documentation provides the entire API specification for managing orders within this infrastructure!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
